### ISSUE TITLE
Crash, Bus error?

### ISSUE THREAD

**Issue by PatrickDattilio** [ExposureSoftware/TEC-Client#53] opened 2015-10-01 23:42 UTC
Fatal Python error: Bus error

Thread 0x00007fef7b2cd700 (most recent call first):
  File "/usr/lib/python3.4/tkinter/**init**.py", line 3111 in insert
  File "/home/pat/dev/TEC-Client/client/clientui.py", line 159 in draw_output
  File "/home/pat/dev/TEC-Client/client/clientui.py", line 125 in parse_output
  File "/home/pat/dev/TEC-Client/client/client.py", line 95 in listen
  File "/usr/lib/python3.4/threading.py", line 868 in run
  File "/usr/lib/python3.4/threading.py", line 920 in _bootstrap_inner
  File "/usr/lib/python3.4/threading.py", line 888 in _bootstrap

Current thread 0x00007fef828f0740 (most recent call first):
  File "/usr/lib/python3.4/tkinter/**init**.py", line 1072 in mainloop
  File "/home/pat/dev/TEC-Client/main.py", line 12 in <module>

**Comment by PatrickDattilio** [comment] 2015-10-03 04:34
Only seems to occur on ubuntu.

**Comment by marshall-davis** [comment] 2015-10-07 06:11
Sure this isn't related to issue #24?

I think this is most likely caused by two threads trying to draw to the UI simultaneously. I need to do thread management better.

**Comment by marshall-davis** [comment] 2015-10-14 02:10
It's strange these aren't being closed when the branch gets merged into `master`.

Closing, hopefully fixed by PR #59

**Closed as completed by marshall-davis** 2015-10-14 02:10 UTC
